# NumPy

**Num**erical **Py**thon es nuestra librería de cabecera, provee la estructura básica *core* que vamos a usar para casi todas las operaciones: el `numpy array`. Este es el vector/matriz/tensor que conocemos en matemática, con todas las propiedades típicas y esperables:

* Todos los elementos tienen el mismo formato (real, entero, etc.)
* La dimensión se fija al momento de definir la variable (pueden cambiar los valores, no las formas).
* Si hacemos cosas como multiplicar por un escalar, la operación se propaga por *broadcasting* a todos los elementos del vector.

Recomendamos fuertemente la lectura (parcial, no total) de la documentación oficial de la librería, tanto la [guía de uso](https://numpy.org/doc/stable/user/whatisnumpy.html) como la [lista de funcionalidades](https://numpy.org/doc/stable/reference/index.html).

[Aquí](https://towardsdatascience.com/the-ultimate-beginners-guide-to-numpy-f5a2f99aef54) hay un buen resumen sobre inicios con NumPy, de mayor extensión que el presente.

[Aquí](https://www.datacamp.com/community/blog/python-numpy-cheat-sheet) hay un pequeño cheatsheet sobre métodos y funciones disponibles en el paquete.

## Creación de `arrays`

Importante: recordemos que los arrays no son necesariamente unidimensionales, pueden ser matrices o tensores de rango superior.

In [ ]:
import numpy as np

a = np.array([[1,2],[3,4]])               # en base a un iterable de python, como es una lista
b = np.arange(start=-1,stop=5, step=2)    # una sucesión de elementos, notar que el stop no es incluido
c = np.linspace(start=0, stop=10, num=5)  # 5 puntos uniformemente distribuidos sobre [0,10], incluido extremos
d = np.empty(shape=(2,3))                 # una matriz de 2x3 sin inicializar (es muy rápido)
e = np.zeros((2,3))                       # una matriz de 2x3 inicializada con 0s

print(a)
print(b)
print(c)
print(d)
print(e)

[[1 2]
 [3 4]]
[-1  1  3]
[ 0.   2.5  5.   7.5 10. ]
[[5.e-324 1.e-323 0.e+000]
 [5.e-324 1.e-323 0.e+000]]
[[0. 0. 0.]
 [0. 0. 0.]]


## Caracterización de un `array`

In [ ]:
# uso de shape para observar las dimensiones de un array
print("a tiene shape:",a.shape)
print("c tiene shape:",c.shape)
print("d tiene shape:",d.shape)


# len nos provee el largo del array (que suele ser la cantidad de filas)
print("a tiene len:",len(a))

# size nos provee la cantidad de elementos del array
print("a tiene size:",a.size)

a tiene shape: (2, 2)
c tiene shape: (5,)
d tiene shape: (2, 3)
a tiene len: 2
a tiene size: 4


## Operaciones simples con `arrays`

Algunas cuestiones importantes en NumPy son que:

* Las operaciones se asumen elemento a elemento (*element-wise*), por ejemplo si $x,y \in \mathbb{R}^5$ entonces también $x · y = (x_1 · y_1, \dots, x_5·y_5) \in \mathbb{R}^5$. Si se quiere el producto escalar, el operador `@` (de producto matricial) o la función `dot` son ambas opciones correctas.
* Si las dimensiones no coinciden, se intenta "expandir" el menor a la dimensión correcta para *propagar* la operación. A esto se lo conoce como *broadcasting* y explica por qué si $x \in \mathbb{R}^3$ entonces $x + 5 = (x_1+5, x_2+5,x_3+5) \in \mathbb{R}^3$.

In [ ]:
# definimos algunos arrays primero
x1 = np.array([1,2,3,4])
x2 = np.array([5,6,7,8])
m1 = np.array([[1,2],[3,4],[5,6]])
y1 = np.array([5,6])
print("x1 =",x1)
print("x2 =",x2)
print("m1 =",m1)
print("y1 =",y1)

x1 = [1 2 3 4]
x2 = [5 6 7 8]
m1 = [[1 2]
 [3 4]
 [5 6]]
y1 = [5 6]


In [ ]:
# suma de vectores
x1+x2

array([ 6,  8, 10, 12])

In [ ]:
# suma con broadcasting
x1+5

array([6, 7, 8, 9])

In [ ]:
# producto de vectores
# observar que es elemento a elemento
x1*x2

array([ 5, 12, 21, 32])

In [ ]:
# producto escalar
x1 @ x2

70

In [ ]:
# e^x1 vectorizado
np.exp(x1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
# suma acumulativa de valores de x1
np.cumsum(x1)

array([ 1,  3,  6, 10])

In [ ]:
# suma de un vector y una matriz con broadcasting
# observar que se 'propaga' fila a fila
m1 + y1

array([[ 6,  8],
       [ 8, 10],
       [10, 12]])

In [ ]:
# trasposición de una matriz
m1.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
# inversa de una matriz
mm = np.array([1,2,3,4,5,7,6,8,9]).reshape((3,3))
print(mm)
mm_inv = np.linalg.inv(mm)
print(mm_inv)

[[1 2 3]
 [4 5 7]
 [6 8 9]]
[[-1.57142857  0.85714286 -0.14285714]
 [ 0.85714286 -1.28571429  0.71428571]
 [ 0.28571429  0.57142857 -0.42857143]]


In [ ]:
# qué pasa si multiplicamos las dos matrices?
mm * mm_inv

array([[-1.57142857,  1.71428571, -0.42857143],
       [ 3.42857143, -6.42857143,  5.        ],
       [ 1.71428571,  4.57142857, -3.85714286]])

In [ ]:
# lo que pasa es que ese no es el producto matricial, y ahora?
mm @ mm_inv

array([[ 1.00000000e+00, -1.11022302e-16, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00, -3.33066907e-16,  1.00000000e+00]])

In [ ]:
# ¿qué pasa si queremos invertir una matriz que no tiene inversa?
xd = np.array([1,2,3,4,5,6]).reshape((2,3))
print(xd)
xd_inv = np.linalg.inv(xd)

[[1 2 3]
 [4 5 6]]


LinAlgError: ignored

## Indexación y vectores lógicos

Llamamos indexar a acceder a elementos de un array, a partir de diversos métodos.

Llamamos vector lógico es un vector compuesto por valores booleanos (*True* o *False*).

### Indexación simple

Se accede a un valor específico de una o más dimensiones utilizando corchetes [ ] para indicar el valor del índice sobre cada una.

**Recordar que el primer elemento siempre lleva índice 0, no 1**

In [ ]:
# recordemos m1
m1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# accedemos al elemento de la 2º fila, 1º columna (indices 1 y 0 respectivamente)
m1[1,0]

3

In [ ]:
# si sólo indicamos 1 índice, recortamos el eje de las filas
# accedemos a la 3º fila, con índice 2
m1[2]

array([5, 6])

In [ ]:
# si queremos acceder a la 1º columna podemos omitir índice en las filas
m1[:,0]

array([1, 3, 5])

### Slicing

Como se vio en el ejemplo anterior, fue necesario introducir un `:` en el índice de las filas para que la sintaxis no sea inválida. En realidad, la indexación simple es un caso particular de *slicing*, esto es, indexación utilizando *rangos de valores* y se hace de la misma manera que el slicing básico de Python, esto es por ejemplo `x[1:5, 3:5]` accede a los valores de las filas 2 a 5 y columnas 4 a 5.

Observar que el rango `m:n` recorre desde *m* hasta *n-1*. Por lo que si se desean los índices *x* a *y* se debe indicar el rango `x-1:y`

Volviendo al ejemplo anterior, `m1[:,0]` indica que se quiere el rango completo de las filas, para columnas de índice 0, lo cual es equivalente a acceder a la primer columna.

In [ ]:
# definimos una nueva matriz más grande
m2 = np.arange(24).reshape(6,4)
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# accedo a las filas 1 a 3 de m2, columnas 2 a 3
m2[0:3, 1:3] 

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

### Indexación por array

El *slicing* es, a su vez, un caso particular de indexación por array, donde se indica con un iterable, índice a índice, cúales elementos acceder sobre un eje.

Observar sin embargo que el slicing preserva las dimensiones, mientras que la indexación por array no (como es de esperarse).

In [ ]:
# accedo a las filas 1 y 3 (pero no 2) de m2, columnas 2 y 4 (pero no 3)
m2[[0,2],[1,3]]

array([ 1, 11])

### Indexación por vectores lógicos

Otra forma de indexación por array es, en vez de un vector que indique los *índices* de los elementos a acceder, un array de la misma dimensionalidad que el original y donde se indica con *True* los valores deseados, y con *False* los no deseados.

En el caso particular en que el vector lógico se construye a partir del mismo array a acceder, estamos incurriendo en un filtrado por valores, pero el mecanismo permite hacer operaciones sobre distintos arrays.

In [ ]:
# quiero sólo los valores impares de m2
m2[m2 % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
# observemos el vector lógico utilizado, tiene la misma forma que m2
m2 % 2 != 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
# qué pasa si miro sólo una columna?
m2[:,1] % 3 != 0

array([ True,  True, False,  True,  True, False])

In [ ]:
# eso lo puedo utilizar para (vía broadcasting) filtrar la matriz vía valores de esa columna!
m2[m2[:,1] % 3 != 0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Jugando a encriptar

Vamos a utilizar un mecanismo de cifrado *inspirado* en el [cifrado Hill](https://es.wikipedia.org/wiki/Cifrado_Hill). En este caso, vamos a utilizar un $n=4$, es decir que nuestra matriz (inversible) de cifrado $K$ va a ser de $\mathbb{R}^{4 \times 4}$.

## Cifrado 

El procedimiento es el siguiente:

1. A nuestro mensaje de $m$ letras le agregamos caracteres de *padding* (relleno) hasta que el largo del mensaje $m'$ es múltiplo de $n$.
2. Utilizando una codificación del alfabeto a números (por ejemplo, $A \rightarrow 1$), convertimos nuestro mensaje paddeado de $m'$ letras a un vector de $\mathbb{R}^{m'}$
3. Seccionamos el vector en *slices* de $n$ elementos, obteniendo el mensaje como una matriz $M \in \mathbb{R}^{n \times \frac{m'}{n}}$.
4. Obtenemos el mensaje cifrado como $E = K \cdot M$

**Para pensar 1: ¿Dónde vive E?**

**Para pensar 2: ¿Por qué es necesario el paso 2?**

## Descifrado

Vamos a suponer que ya disponemos de la inversa $K^{-1}$. Veamos que el procedimiento para descifrar es exactamente inverso al de cifrado:

1. Obtenemos el mensaje descifrado $M_2 = K^{-1} \cdot E$
2. Aplanamos la matriz $M_2 \in \mathbb{R}^{n \times \frac{m'}{n}}$ para obtener un vector de $\mathbb{R}^{m'}$
3. Decodificamos el vector para obtener el mensaje paddeado de largo $m'$.
4. Quitamos todos los caracteres de padding que encontremos al final del mensaje.


**Para pensar 3: ¿Por qué estamos tan seguros que $M_2 = M$?**

In [ ]:
# esto no importa
def print2(*args):
  print(*args, end='\n\n')

In [ ]:
# construimos el encoder y decoder del alfabeto
from string import ascii_lowercase

PADDING_CHAR = '.'
alfabeto = ascii_lowercase+' '+ PADDING_CHAR # las letras + espacio + caracter de padding "."

# enumerate itera sobre un iterable pero ademas nos da el indice
# es decir, (0,a)->(1,b)-> ... ->(27, .)
encoder = {letter: idx for idx, letter in enumerate(alfabeto)}
print(encoder)

# forma fácil y rápida de invertir un diccionario, ya que items() nos da los pares (clave,valor)
decoder = {v:k for k,v in encoder.items()}

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25, ' ': 26, '.': 27}


In [ ]:
# construimos las funciones para acomodar largos
def add_padding(message, padd_char, n):
  """
  Add padd_char characters to the message until len(message) is a multiple of n.
  n must be an integer greater than 1 and len(padd_char) must be exactly 1.
  """
  # si el largo del mensaje ya es multiplo de n, devolver el mensaje tal cual
  if len(message) % n == 0:
    return message
  # si no, le sobran len(message) % n caracteres (y por tanto le faltan n - eso para completar)
  how_many_padds = n - len(message) % n 

  # recordar que la multiplicacion en Python para strings es la concatenacion
  # por ej. 3 * 'A' = 'AAA'
  return message + how_many_padds * padd_char

def remove_padding(message, padd_char):
  return message.rstrip(padd_char)

In [ ]:
# definimos el mensaje y la clave K
import numpy.linalg as npl

mensaje = "alo vero como andas"

K = np.array([
              [1,2,3,4],
              [5,4,4,6],
              [2,1,1,3],
              [1,2,1,1]
])

N = 4

# chequeamos que sea inversible
npl.det(K)

-14.999999999999993

In [ ]:
# Obtenemos la matriz M
print2(f"Mensaje original (largo = {len(mensaje)}): {mensaje}")

mensaje_con_padding = add_padding(mensaje, PADDING_CHAR, N)

print2(f"Mensaje con padding (largo = {len(mensaje_con_padding)}): {mensaje_con_padding}")

mensaje_encodeado = [encoder[letra] for letra in mensaje_con_padding]

print2(f"Mensaje encodeado: {mensaje_encodeado}")

# pasamos el mensaje a matriz de n filas

M = np.array(mensaje_encodeado, dtype=int).reshape(N, len(mensaje_encodeado)//N)

print("Mensaje como matriz M:")
print2(M)

Mensaje original (largo = 19): alo vero como andas

Mensaje con padding (largo = 20): alo vero como andas.

Mensaje encodeado: [0, 11, 14, 26, 21, 4, 17, 14, 26, 2, 14, 12, 14, 26, 0, 13, 3, 0, 18, 27]

Mensaje como matriz M:
[[ 0 11 14 26 21]
 [ 4 17 14 26  2]
 [14 12 14 26  0]
 [13  3  0 18 27]]



In [ ]:
# Encriptamos utilizando la matriz
E = K @ M

print("Mensaje encriptado E:")
print(E)

Mensaje encriptado E:
[[102  93  84 228 133]
 [150 189 182 446 275]
 [ 57  60  56 158 125]
 [ 35  60  56 122  52]]


In [ ]:
# Para desencriptar necesitamos la inversa de K

K_inv = npl.inv(K)
print(K_inv)

[[-0.4         0.46666667 -0.26666667 -0.4       ]
 [ 0.         -0.33333333  0.33333333  1.        ]
 [ 0.2         0.6        -1.2        -0.8       ]
 [ 0.2        -0.4         0.8         0.2       ]]


In [ ]:
# Desencriptamos

# multiplicamos por la inversa de K, comparar M2 contra M
M2_ = K_inv @ E

print("M desencriptada:")
print2(M2_)

# EPA! hay problemas de redondeo culpa de la computadora... pero nada muy grave, redondeamos
M2 = np.rint(M2_).astype(int)

print("Ahora sí, M desencriptada")
print2(M2)

# no nos confiemos, M2 y M son iguales?
assert np.all(M2 == M)

# perfecto! ahora aplanamos
mensaje_aplanado = M2.flatten()

print2(f"M2 aplanada: {mensaje_aplanado}")

# desconvertimos
mensaje_desencodeado = "".join([decoder[num] for num in mensaje_aplanado])

print2(f"Mensaje recuperado con padding (largo = {len(mensaje_con_padding)}): {mensaje_con_padding}")

# quitamos padding
mensaje_sin_padding = remove_padding(mensaje_desencodeado, PADDING_CHAR)

print2(f"Mensaje recuperado (largo = {len(mensaje_sin_padding)}): {mensaje_sin_padding}")

M desencriptada:
[[-8.38218384e-15  1.10000000e+01  1.40000000e+01  2.60000000e+01
   2.10000000e+01]
 [ 4.00000000e+00  1.70000000e+01  1.40000000e+01  2.60000000e+01
   2.00000000e+00]
 [ 1.40000000e+01  1.20000000e+01  1.40000000e+01  2.60000000e+01
  -1.24344979e-14]
 [ 1.30000000e+01  3.00000000e+00  1.99840144e-15  1.80000000e+01
   2.70000000e+01]]

Ahora sí, M desencriptada
[[ 0 11 14 26 21]
 [ 4 17 14 26  2]
 [14 12 14 26  0]
 [13  3  0 18 27]]

M2 aplanada: [ 0 11 14 26 21  4 17 14 26  2 14 12 14 26  0 13  3  0 18 27]

Mensaje recuperado con padding (largo = 20): alo vero como andas.

Mensaje recuperado (largo = 19): alo vero como andas



### ¿Qué pasa si se intenta utilizar una clave incorrecta?


In [ ]:
K_mala = K + 1
print("Clave incorrecta: ")
print2(K_mala)

# intentamos descifrar utilizando esa clave
remove_padding("".join([decoder[i] for i in np.rint(inv(K_mala) @ E).astype(int).flatten()]), PADDING_CHAR)

Clave incorrecta: 
[[2 3 4 5]
 [6 5 5 7]
 [3 2 2 4]
 [2 3 2 2]]



KeyError: ignored

¡Ni siquiera da un string válido! E incluso si devolviera uno, no va a dar nada parecido al original.

## Para jugar en casa: versión OOP

Es (casi) exactamente lo mismo que antes pero utilizando clases y métodos.

No les vamos a decir cómo funciona, solamente les vamos a dar una ayuda: se puede registrar en dos modos: 
1. Pasar una key al inicio y utilizar siempre esa *(ó...)*
2. Utilizar una clave aparte para cada operación de cifrado+descifrado.

¡A descifrar (el código)!

In [ ]:
import numpy as np
from numpy.linalg import inv, det

class MatrixCipher(object):
  def __init__(self, alphabet, padding_char, key=None):
    """
    Params:
    alphabet (str): a string with all the characters allowed in a message (they must all be different).
    padding_char (str): the character to be used for padding. Must not be included in alphabet.
    key (n x n matrix, optional): an invertible matrix to be used as key. 
    
    If key is passed, key arguments in cipher and decipher will be ignored.
    """
    assert len(alphabet) == len(set(alphabet)), "Alphabet has non-unique characters"
    assert padding_char not in alphabet, "Padding char is included in the alphabet"
    if key is not None:
      assert len(key.shape) == 2, "Key is not a matrix"
      assert key.shape[0] == key.shape[1], "Key is not a square matrix"
      assert det(key) != 0, "Key is not invertible"

    self.encoder = {letter: idx for idx, letter in enumerate(alphabet + padding_char)}
    self.decoder = {v:k for k,v in self.encoder.items()}
    self.padding = padding_char
    self.key = key

  def _try_get_key(self, key):
    key = key if self.key is None else self.key
    assert key is not None, "Key was neither initialized nor passed"
    return key

  def _matrixify(self, message, n):
    if len(message) % n != 0:
      message += self.padding * (n - len(message) % n)
    
    encoded_msg = [self.encoder[x] for x in message]

    return np.array(encoded_msg).reshape(n, len(encoded_msg)//n)

  def cipher(self, message, key=None):
    K = self._try_get_key(key)

    n = K.shape[0]

    M = self._matrixify(message, n)

    return K @ M
  
  def _dematrixify(self, matrix):
    decoded_vector = [self.decoder[x] for x in np.rint(matrix.flatten())]
    return "".join(decoded_vector).rstrip(self.padding)

  def decipher(self, ciphered_message, key=None):
    K = self._try_get_key(key)

    K_inv = inv(K)

    M = K_inv @ ciphered_message

    return self._dematrixify(M)

In [ ]:
# el ejemplo de antes tiene su equivalente en este cipher
mi_cipher = MatrixCipher(alphabet=ascii_lowercase+" ",padding_char=PADDING_CHAR, key=K)